import {
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Banknote,
  Bus,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  Clock,
  CreditCard,
  Cross,
  HelpCircle,
  Home,
  Info,
  Landmark,
  IndianRupee,
  LockKeyhole,
  Moon,
  PartyPopper,
  PencilLine,
  Plane,
  Plus,
  ReceiptText,
  Repeat,
  ScanFace,
  Settings,
  Shapes,
  Shirt,
  ShoppingBasket,
  Smartphone,
  TrendingUp,
  Type,
  Vibrate,
  Trash2,
  Tv,
  User,
  Utensils,
  Wallet,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

/** Name → icon, covering every icon named in the handoff. */
const ICONS: Record<string, ComponentType<LucideProps>> = {
  'alert-triangle': AlertTriangle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  banknote: Banknote,
  bus: Bus,
  calendar: Calendar,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-check': CircleCheck,
  clock: Clock,
  'credit-card': CreditCard,
  cross: Cross,
  'help-circle': HelpCircle,
  home: Home,
  info: Info,
  landmark: Landmark,
  'indian-rupee': IndianRupee,
  'lock-keyhole': LockKeyhole,
  moon: Moon,
  'party-popper': PartyPopper,
  'scan-face': ScanFace,
  'pencil-line': PencilLine,
  plane: Plane,
  plus: Plus,
  'receipt-text': ReceiptText,
  repeat: Repeat,
  settings: Settings,
  shapes: Shapes,
  shirt: Shirt,
  'shopping-basket': ShoppingBasket,
  smartphone: Smartphone,
  'trending-up': TrendingUp,
  type: Type,
  vibrate: Vibrate,
  'trash-2': Trash2,
  tv: Tv,
  user: User,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export function Icon({ name, size = 18, ...rest }: { name: string; size?: number } & LucideProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp size={size} strokeWidth={1.8} aria-hidden="true" {...rest} />;
}
