import {
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Baby,
  Banknote,
  BarChart3,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  Clock,
  Coffee,
  CreditCard,
  Cross,
  Dog,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HelpCircle,
  Home,
  Hotel,
  House,
  IndianRupee,
  Info,
  Landmark,
  Laptop,
  Lightbulb,
  LockKeyhole,
  Moon,
  Music,
  PartyPopper,
  PencilLine,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Plus,
  Receipt,
  ReceiptText,
  Repeat,
  ScanFace,
  Scissors,
  Settings,
  Shapes,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Tag,
  Ticket,
  TrainFront,
  Trash2,
  TrendingUp,
  Tv,
  Type,
  Umbrella,
  User,
  Utensils,
  Vibrate,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

/** Name → icon, covering every icon named in the handoff. */
const ICONS: Record<string, ComponentType<LucideProps>> = {
  'coffee': Coffee,
  'pizza': Pizza,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'gift': Gift,
  'car': Car,
  'fuel': Fuel,
  'train-front': TrainFront,
  'bike': Bike,
  'hotel': Hotel,
  'house': House,
  'sofa': Sofa,
  'lightbulb': Lightbulb,
  'wifi': Wifi,
  'gamepad-2': Gamepad2,
  'film': Film,
  'music': Music,
  'ticket': Ticket,
  'beer': Beer,
  'heart': Heart,
  'pill': Pill,
  'stethoscope': Stethoscope,
  'dumbbell': Dumbbell,
  'shield': Shield,
  'umbrella': Umbrella,
  'receipt': Receipt,
  'piggy-bank': PiggyBank,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'baby': Baby,
  'dog': Dog,
  'scissors': Scissors,
  'sparkles': Sparkles,
  'wrench': Wrench,
  'briefcase': Briefcase,
  'plug': Plug,
  'laptop': Laptop,
  'tag': Tag,
  'alert-triangle': AlertTriangle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  banknote: Banknote,
  bus: Bus,
  calendar: Calendar,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-check': CircleCheck,
  clock: Clock,
  'credit-card': CreditCard,
  cross: Cross,
  'help-circle': HelpCircle,
  home: Home,
  info: Info,
  landmark: Landmark,
  'indian-rupee': IndianRupee,
  'lock-keyhole': LockKeyhole,
  moon: Moon,
  'party-popper': PartyPopper,
  'scan-face': ScanFace,
  'pencil-line': PencilLine,
  plane: Plane,
  plus: Plus,
  'receipt-text': ReceiptText,
  repeat: Repeat,
  settings: Settings,
  shapes: Shapes,
  shirt: Shirt,
  'shopping-basket': ShoppingBasket,
  smartphone: Smartphone,
  'trending-up': TrendingUp,
  type: Type,
  vibrate: Vibrate,
  'trash-2': Trash2,
  tv: Tv,
  user: User,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export function Icon({ name, size = 18, ...rest }: { name: string; size?: number } & LucideProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp size={size} strokeWidth={1.8} aria-hidden="true" {...rest} />;
}
